import 'records/domain/entities/resource_spec.dart';

/// true  = sign in with the Elyvori API and show the live agents dashboard.
/// false = a standalone offline-first app that opens straight on its modules.
const bool useElyvoriAgents = false;

/// The modules of this app, generated by Elyvori from the client's request.
const List<ResourceSpec> appResources = <ResourceSpec>[
  ResourceSpec(
    key: 'members',
    title: 'الأعضاء',
    icon: 'people',
    description: 'إدارة أعضاء النادي الرياضي',
    fields: [
      FieldSpec(key: 'full_name', label: 'اسم العضو', type: FieldType.text, required: true),
      FieldSpec(key: 'phone_number', label: 'رقم الهاتف', type: FieldType.phone, required: true),
      FieldSpec(key: 'email', label: 'البريد الإلكتروني', type: FieldType.email, required: false),
      FieldSpec(key: 'join_date', label: 'تاريخ التسجيل', type: FieldType.date, required: true),
      FieldSpec(key: 'is_active', label: 'حساب نشط', type: FieldType.boolean, required: true),
    ],
  ),
  ResourceSpec(
    key: 'subscriptions',
    title: 'الاشتراكات',
    icon: 'money',
    description: 'إدارة اشتراكات وباقات الأعضاء',
    fields: [
      FieldSpec(key: 'subscription_name', label: 'اسم الباقة', type: FieldType.text, required: true),
      FieldSpec(key: 'member_name', label: 'اسم العضو', type: FieldType.text, required: true),
      FieldSpec(key: 'price', label: 'السعر', type: FieldType.number, required: true),
      FieldSpec(key: 'start_date', label: 'تاريخ البداية', type: FieldType.date, required: true),
      FieldSpec(key: 'end_date', label: 'تاريخ النهاية', type: FieldType.date, required: true),
    ],
  ),
  ResourceSpec(
    key: 'classes',
    title: 'الحصص',
    icon: 'calendar',
    description: 'جدولة حصص التدريب الجماعي',
    fields: [
      FieldSpec(key: 'class_name', label: 'اسم الحصة', type: FieldType.text, required: true),
      FieldSpec(key: 'trainer_name', label: 'اسم المدرب', type: FieldType.text, required: true),
      FieldSpec(key: 'class_date', label: 'موعد الحصة', type: FieldType.date, required: true),
      FieldSpec(key: 'max_capacity', label: 'الحد الأقصى للمشاركين', type: FieldType.number, required: true),
      FieldSpec(key: 'notes', label: 'ملاحظات', type: FieldType.longText, required: false),
    ],
  ),
];
